export const ACTIONS = {
  LOADING_SHOPING_LIST: 'LOADING_SHOPING_LIST',
  LOADING_SHOPING_LIST_SUCCESS: 'LOADING_SHOPING_LIST_SUCCESS',
  LOADING_SHOPING_LIST_ERROR: 'LOADING_SHOPING_LIST_ERROR',
  LOADING_SHOPING_LIST_BY_ID: 'LOADING_SHOPING_LIST_BY_ID',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_FAILED: 'LOGIN_REQUEST_FAILED',
  LOGOUT: 'LOGOUT',
  LOADING_STATISTIC: 'LOADING_STATISTIC',
  LOADING_STATISTIC_SUCCESS: 'LOADING_STATISTIC_SUCCESS',
  LOADING_STATISTIC_ERROR: 'LOADING_STATISTIC_ERROR',
  LOGIN: 'LOGIN',
  SET_DATE: 'SET_DATE'
}